### ISSUE TITLE
All: добавить поддержку прокси с возможностью частичного использования

### ISSUE THREAD

**Issue by SadFrozz** [vitalygashkov/streamyx#100]
Очень нехватает поддержки прокси HTTPS и SOCKS5. Реализацию предлагаю следующую:
в случае если прокси будет для всех сервисов, то файл proxy.json в каталоге /config/, если для конкретного сервиса, то /config/service_name/. Формат прокси общепринятый, protocol://[login:password@]ip_or_domain:port (то что указано в скобках параметр не обязательный, но он должен поддерживаться, т.к. некоторые прокси требуют авторизацию.

Касаемо логики работы. Пихать прокси на все процессы, начиная от парсинга и заканчивая скачиванием, так себе идея, т.к. в случае резидентных прокси обьем трафика лимитирован и каждый мегабайт на счету. Потому предлагаю следующее:
В файле proxy.json первым должен быть параметр usage c 3 переменными
full - использование прокси для всего, необходимо при работе с особо параноидальными сервисами, которым только один ip подавай.
partial - прокси используется для первичного парсинга релиза и проверки релиза, скачивание аудио- и видеопотоков происходит в обход прокси.
none - прокси не используется, полезно при временном отключении прокси, но необходимо сохранить само прокси в файле

**Comment by vitalygashkov** [comment]
В v4 добавлена поддержка HTTP(S) прокси:
Для всех запросов: `--proxy`
Для получения метаданных и прочей информации о потоках: `--proxy-meta`
Для скачивания видео/аудио/субтитров: `--proxy-media`

Протокол SOCKS5 и отдельные прокси на каждый сервис будут реализованы позже. Можно завести отдельные тикеты на эти фичи.
