### ISSUE TITLE
v4.0.0-beta.5. Okko. Crash

### ISSUE THREAD

**Issue by IIeTp** [vitalygashkov/streamyx#121]
`streamyx.exe https://okko.tv/serial/boonie-squad/season/2`
```
2024-4-19 18:32:30 DEBUG  Manifest URL: http://cdp17.cdn.okko.tv/data/cid/255864990-1713708905-jTv3HMjWhf8uufwuS2NuPQ/storage114/clr/m/shfe/0af01a41-9cee-41f9-8050-837968961449/output.ism/Manifest.mpd
2024-4-19 18:32:30 INFO   Boonie Squad ∙ S2 ∙ E45
2024-4-19 18:32:32 DEBUG  Retry 1/3: http://cdp17.cdn.okko.tv/data/cid/255864990-1713708905-jTv3HMjWhf8uufwuS2NuPQ/storage114/clr/m/shfe/0af01a41-9cee-41f9-8050-837968961449/output.ism/Manifest.mpd
2024-4-19 18:32:33 DEBUG  Retry 2/3: http://cdp17.cdn.okko.tv/data/cid/255864990-1713708905-jTv3HMjWhf8uufwuS2NuPQ/storage114/clr/m/shfe/0af01a41-9cee-41f9-8050-837968961449/output.ism/Manifest.mpd
2024-4-19 18:32:35 DEBUG  Retry 3/3: http://cdp17.cdn.okko.tv/data/cid/255864990-1713708905-jTv3HMjWhf8uufwuS2NuPQ/storage114/clr/m/shfe/0af01a41-9cee-41f9-8050-837968961449/output.ism/Manifest.mpd
```
[log.txt](https://github.com/vitalygashkov/streamyx/files/15042764/log.txt)

**Comment by IIeTp** [comment]
beta 14
```
2024-4-29 21:01:48 INFO   Saiyuuki Reload: Zeroin ∙ S1 ∙ E13
C:\snapshot\streamyx\dist\src\downloader.js:115
    const manifest = await (0, dasha_1.parse)(patchedManifest, response.url, fallbackLanguage);
                                             ^

Error: Invalid manifest
    at parse (C:\snapshot\streamyx\packages\dasha\dasha.js)
    at fetchManifest (C:\snapshot\streamyx\dist\src\downloader.js:115:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Downloader.start (C:\snapshot\streamyx\dist\src\downloader.js:133:26)
    at async Object.download (C:\snapshot\streamyx\dist\src\streamyx.js:53:17)
    at async start (C:\snapshot\streamyx\dist\src\main.js:43:9)

Node.js v20.11.1
```
[202404291751_21468.log](https://github.com/vitalygashkov/streamyx/files/15153030/202404291751_21468.log)

**Comment by IIeTp** [comment]
```
2024-5-4 1:14:54 INFO   Platinum End ∙ S2 ∙ E8 ∙ Symbol of Promise
2024-5-4 1:14:56 INFO   √ VIDEO ∙ 1920x1080 ∙ 7986 KiB/s ∙ ~1448 MiB
2024-5-4 1:15:59 INFO   × AUDIO ∙ RU-RU ∙ 128 KiB/s ∙ ~23 MiB
2024-5-4 1:16:06 ERROR  Download failed: content-range mismatch
```
[202405032234_22688.log](https://github.com/vitalygashkov/streamyx/files/15205602/202405032234_22688.log)
[202405032222_95772.log](https://github.com/vitalygashkov/streamyx/files/15205603/202405032222_95772.log)
[202405032216_95460.log](https://github.com/vitalygashkov/streamyx/files/15205604/202405032216_95460.log)
[202405032203_90620.log](https://github.com/vitalygashkov/streamyx/files/15205605/202405032203_90620.log)
одинаковая ошибка, при повторной загрузке всё норм

**Comment by vitalygashkov** [comment]
> ```
> 2024-5-4 1:14:54 INFO   Platinum End ∙ S2 ∙ E8 ∙ Symbol of Promise
> 2024-5-4 1:14:56 INFO   √ VIDEO ∙ 1920x1080 ∙ 7986 KiB/s ∙ ~1448 MiB
> 2024-5-4 1:15:59 INFO   × AUDIO ∙ RU-RU ∙ 128 KiB/s ∙ ~23 MiB
> 2024-5-4 1:16:06 ERROR  Download failed: content-range mismatch
> ```
> 
> [202405032234_22688.log](https://github.com/vitalygashkov/streamyx/files/15205602/202405032234_22688.log) [202405032222_95772.log](https://github.com/vitalygashkov/streamyx/files/15205603/202405032222_95772.log) [202405032216_95460.log](https://github.com/vitalygashkov/streamyx/files/15205604/202405032216_95460.log) [202405032203_90620.log](https://github.com/vitalygashkov/streamyx/files/15205605/202405032203_90620.log) одинаковая ошибка, при повторной загрузке всё норм

Это уже другая ошибка. Имею в виду, что в первых сообщениях речь о том, что не удаётся получить MPD манифест, а в этом - ошибка скачивания одного из сегментов медиа-контента. Её лучше выделить в отдельный Issue. Возможно, ошибка с `content-range mismatch` пройдёт в `v4beta18`, но если нет, то стоит завести отдельный Issue. Кстати, в приложенных логах почему-то не вижу именно этой ошибки `content-range mismatch`..

**Comment by IIeTp** [comment]
@vitalygashkov да я решил, может не стоит плодить мне эти issue, чет от меня их много, но хозяин - барин, поступлю как скажете. да, не видно, не пишется в лог просто. подозреваю, что эта ошибка связана с папкой tmp, она повторяется регулярно, если не успела очиститься. скорее всего ошибка из-за этого и появляется, надо может проверить, точно ли папка очищается. с чистой папкой не удалось словить такую ошибку
