### ISSUE TITLE
v4.0.0-beta.5. Crunchyroll. Ищет серии, которых нет в сезоне

### ISSUE THREAD

**Issue by IIeTp** [vitalygashkov/streamyx#129]
Четвертый сезон начинается с 207 серии. Возможно в этом причина такого поведения. Полные логи можно будет найти в соседнем issue
`streamyx https://www.crunchyroll.com/ru/series/GRMG8ZQZR/one-piece -e s04e257-300`
```2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found
2024-4-22 4:30:40 ERROR  No suitable streams found...
```

**Comment by vitalygashkov** [comment]
Проблема повторяется, если ввести аргумент с эпизодами в [правильном формате](https://github.com/vitalygashkov/streamyx/issues/131#issuecomment-2070402108)?

**Comment by IIeTp** [comment]
в последних бетах всё ок
