### ISSUE TITLE
Decryption error when file path is longer than 255 characters (Windows)

### ISSUE THREAD

**Issue by vitalygashkov** [vitalygashkov/streamyx#148]
Command example:
```
streamyx -q 360p -e S01E01 https://wink.ru/series/vysokoskorostnaya-etual-year-2024
```

`shaka-packager` command example:
```
C:\streamyx\files\packager-win-x64.exe "input=C:\Users\test\Downloads\Высокоскоростная.этуаль.S01.360p.WINK.WEB-DL.x264\Высокоскоростная.этуаль.S01E01.1-я.серия.360p.WINK.WEB-DL.x264.a3285274820-s35761.cdn.ngenix.net-video-avc1.64001e-1395164-period-video_640x360_b9c3acb1-video.ets-video-v1.enc.mp4,stream=video,output=C:\Users\test\Downloads\Высокоскоростная.этуаль.S01.360p.WINK.WEB-DL.x264\Высокоскоростная.этуаль.S01E01.1-я.серия.360p.WINK.WEB-DL.x264.a3285274820-s35761.cdn.ngenix.net-video-avc1.64001e-1395164-period-video_640x360_b9c3acb1-video.ets-video-v1.dec.mp4" --enable_raw_key_decryption --keys "key_id=ce513f999fbd46919b585e335b81bb77:key=af5683f35bf95bd648d45c0b3dc8e0ca"
I0505 12:13:24.213364   22540 demuxer.cc:94] Demuxer::Run() on file 'C:\Users\test\Downloads\????????????????.??????.S01.360p.WINK.WEB-DL.x264\????????????????.??????.S01E01.1-?.?????.360p.WINK.WEB-DL.x264.a3285274820-s35761.cdn.ngenix.net-video-avc1.64001e-1395164-period-video_640x360_b9c3acb1-video.ets-video-v1.enc.mp4'.
I0505 12:13:24.217739   22540 demuxer.cc:160] Initialize Demuxer for file 'C:\Users\test\Downloads\????????????????.??????.S01.360p.WINK.WEB-DL.x264\????????????????.??????.S01E01.1-?.?????.360p.WINK.WEB-DL.x264.a3285274820-s35761.cdn.ngenix.net-video-avc1.64001e-1395164-period-video_640x360_b9c3acb1-video.ets-video-v1.enc.mp4'.
E0505 12:13:24.229908    5708 packager_main.cc:628] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading C:\Users\test\Downloads\????????????????.??????.S01.360p.WINK.WEB-DL.x264\????????????????.??????.S01E01.1-?.?????.360p.WINK.WEB-DL.x264.a3285274820-s35761.cdn.ngenix.net-video-avc1.64001e-1395164-period-video_640x360_b9c3acb1-video.ets-video-v1.enc.mp4
```

**Comment by IIeTp** [comment]
я бы просто отрезал русское название. все равно в папке tmp вся магия идет, раз она чистится, то проблем в теории минимум (по уникальности данных для каждой серии)

**Comment by vitalygashkov** [comment]
> я бы просто отрезал русское название. все равно в папке tmp вся магия идет, раз она чистится, то проблем в теории минимум (по уникальности данных для каждой серии)

Папка tmp теперь находится в конфиг файле, поэтому пользователь может указать другой путь, уже с кириллицей в строке. Так что, думаю, нужен другой способ.

**Comment by vitalygashkov** [comment]
> можно также в tmp помещать mkv, затем переносить по пути из конфига. это сработает, если в пути streamyx нет кириллицы

Я имею в виду, что в settings.json теперь можно редактировать путь до папки с временными файлами и до папки с загрузками. И пользователь туда может вписать любой путь, включая тот, в котором есть кириллица. А если перемещать скачанные дорожки куда-то в другое место на своё усмотрение, то это будет не очень корректным поведением, вводя пользователя в заблуждение - по факту указаные одни пути, а прога будет в процессе перемещать файлы по другому пути.

**Comment by IIeTp** [comment]
я понимаю. получается, если пользователь укажет путь с кириллицей для временных файлов, то даже переименование файла в латиницу не поможет. единственное, что можно сделать, так это убрать кириллицу в файлах для шаки имхо

**Comment by vitalygashkov** [comment]
> проблема не в shaka, а в терминале chcp 65001 поможет, чтобы убрать кракозябры

Да, неверно определил причину. Запустил ещё несколько раз и убедился - дешифрует корректно и без смены кодировки, а вот ошибка возникает, когда длина пути выше 255 символов. Фикс, который раньше делал и откатывал на деле работает нормально и устраняет ошибку. В следующем релизе его добавлю обратно.
