### ISSUE TITLE
Не качает аудиодорожки

### ISSUE THREAD

**Issue by novice161** [vitalygashkov/streamyx#194]
При выборе языка аудио параметром -l "ru" к примеру - звуковая дорожка не качается.

**Comment by vitalygashkov** [comment]
Чтобы воспроизвести ошибку мне нужен файл лога с деталями. Он в папке logs рядом с исполняемым файлом.

**Comment by novice161** [comment]
[streamyx_2024-08-12_08-26-37_17104.log](https://github.com/user-attachments/files/16579346/streamyx_2024-08-12_08-26-37_17104.log)
