### ISSUE TITLE
What's the point?

### ISSUE THREAD

**Issue by okaneyo** [vitalygashkov/streamyx#197]
What's the point if you're hiding the src/app folder?
Atleast explain how to fucking call the command to download the stream.
You're doggy executable is probably stealing streaming accounts. 
Fucker

**Comment by vitalygashkov** [comment]
> What's the point if you're hiding the src/app folder?

I'm developing a GUI version in parallel, which uses some of the code from `./src/app`. Later, when I split the code between GUI and CLI, I will partially open sources for CLI.

> Atleast explain how to fucking call the command to download the stream.

README does not provide enough information? Just call the executable and give the URL as an unnamed argument.
`.\streamyx.exe https://www.crunchyroll.com/ru/watch/G65PJWDQ6/the-young-man-on-the-shooting-range`
For information on available options, you can call help: `.\streamyx.exe -h`

> You're doggy executable is probably stealing streaming accounts.

Think what you want. Someone who really fears account theft can check the app with any sniffer and won't see any weird HTTP requests sending logins/passwords.

**Comment by okaneyo** [comment]
I wouldn't put it past you, I saw your older version used puppeteer (real subtle)
Your README is the worst online, you're proud of that? Your TS Node module external dependencies are all out of wack. 
Your blackbox executable doesn't work with CRoll (user-agent) not set
Your CRoll module works, for making authenticated API calls but your test is only to get video meta data. (useless)
So I thought okay well I can add the croll-module to build streamyx myself but no.. you exclude the src/app folder to prevent that. That's also the code that would have shown me how I extend the Steamyx.CRoll API in the module to download videos directly from there. This is a new low, just put this shit on BS GitLab, oh but no.. you wouldn't be able to get installs of your mystery executable if you did that. Fuck you, fuck your bullshit pie in the sky paid UI coming soon and fuck Ukraine. 
You need to be slapped for not doing this in python as well.

**Comment by vitalygashkov** [comment]
> So I thought okay well I can add the croll-module to build streamyx myself but no..

Yes, at the moment I don't fully disclose the source code, so building your own streamyx executable won't work. But I never promised anywhere that you can build something from this open sources. The part that is open source is just for viewing.

> Your CRoll module works, for making authenticated API calls but your test is only to get video meta data. (useless)

Why is it useless? The point is that an outsider can write logic for a new service, and later I can add this service to Streamyx.

> fuck Ukraine

Agreed.

> You need to be slapped for not doing this in python as well.

I write code in whatever language I want. You want python, go ahead and write your solution.

**Comment by okaneyo** [comment]
I thought I'd be downloading endless anime by now but I can't due to your sneaky Github tactics. There's absolutely zero point in contributing to a shady partial project like this nor is it possible. You did most of the difficult work on your CRoll module, true. Which is why I'm so baffled you'd leave people in limbo.  So you're gonna force me to fork your code? Fine whatever.. I'm going to interface based off Axios instead of using Streamyx.core for starters. I'M NOT HAPPY ABOUT THIS!
