### ISSUE TITLE
MPD muxing failed with `.ttml` subs inside

### ISSUE THREAD

**Issue by rinrinx** [vitalygashkov/streamyx#202]
URL: https://files.borfin.com/watch/NDAzMzVkYjFmZGNlYmU5ZjUxNzBlZjE1MWNhZDJmNWFjYjk2MzA5NmE1MDU3YzExMjg2NGY5YThjNGMyNjhiYzlkY2VjMGQyMzY5ZDBlZjU2ZGFiMjIwNjE2NTM2YWVh/public/video/2210/bbfbd25a017b480fa3987a6f48faccd6/dash/stream.mpd
2024-8-30 23:17:35 ERROR  Suitable plugin not found

**Comment by vitalygashkov** [comment]
Use the [beta version 4](https://github.com/vitalygashkov/streamyx/releases/tag/v4.0.0-beta.63) for now. There will be a release soon.

**Comment by rinrinx** [comment]
C:\Users\xxx\OneDrive\Masaüstü>sx.exe https://turkey-edge5.mubicdn.net/stream/c5005d5d4273f82d0415d93ca8584225/66d3be41/bf9cdc15/mubi-films/398452/faruk_tur_zxx_1920x960_50000_mezz45254/7e0b2b450a/drm_playlist.e19c2de7ee.ism/default/ver1.AVC1.2160p.ex-eac3.mpd
20:07:24.644 FATAL: Uncaught exception
    err: {
      "type": "TypeError",
      "message": "m.group is not a function",
      "stack":
          TypeError: m.group is not a function
              at parseLanguage (C:\snapshot\streamyx\packages\dasha\lib\dash.js:93:29)
              at Object.parseManifest (C:\snapshot\streamyx\packages\dasha\lib\dash.js:292:24)
              at parse (C:\snapshot\streamyx\packages\dasha\dasha.js)
              at fetchManifest (C:\snapshot\streamyx\dist\src\app\downloader.js)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Downloader.start (C:\snapshot\streamyx\dist\src\app\downloader.js)
              at async Object.download (C:\snapshot\streamyx\dist\src\app\app.js)
              at async startCli (C:\snapshot\streamyx\dist\src\app\main.js)
    }

**Comment by rinrinx** [comment]
C:\Users\xxx\OneDrive\Masaüstü>sx.exe https://switch-api.tvplus.com.tr/pv/176.235.2.73:80/izmottrrs.tvplus.com.tr/88888888/16/20240815/268591865/268591865.mpd?allcentermount=30,1000001&130,1000002=&rrsip=gbzottrrs.tvplus.com.tr:443&zoneoffset=0&devkbps=190-15000&servicetype=0&servicetype=0&limitflux=-1&limitdur=-1&tenantId=9001&GuardEncType=2&from=31&validdev=5270,5510&hms_devid=5270&pbf=2_1_1_3382915255&vqe=3&app_version=chrome,WebTV,OSVersion=Win32,AppVersion=5.2.6.1,webtv&custom_sid=MTAxMjA2MjA2Nzg3&uid=pgkYL5eEYIhLfFmM6XZOQQ&sw_lh=9nA2sphTybCAls4_k-dq0Q&srv=cHYtYXZyLXMwMi50dnBsdXMuY29tLnRy&sw_h1=U5UTjIXVOCkNwRS3sXVrKg&srv2=cHYtYXZyLXMwMS50dnBsdXMuY29tLnRy&sw_h2=1nmVCIL2PoBgujVTj2QRYg&proxy=true&sw_st=yEv7-Lq6OV33UGKnotvsGoNI5g6tNdnWsIvR_Ddu_Zk&st=OrgoJor2lGAsiB439Aw9aWEiXuVNScyPgf3XKDxBUTI&accountinfo=MC69Mu6X0e+zyQL8Aa6VVTQRgAVp0WMvVhVv9ROGG3p3dSpffkYLK+7yjdk%2FZKfRyUb6HGJ9WB6MX3WLJ2i+BjvpPpen5Og5TgElqK4XPigck64KeYOcZ98QNWG%2Faba6KLAA7Q86GebOs+46M+6x6dsfWNvKG78avpiG0Eh9H0QvltXevcrQbI%2FmCSMmqY%2FG%3A20240831170809%3AUTC%2C%2C%2C20240831170809%2CMBOX020240815%2C%2C-1%2C1%2C0%2C%2C%2C1%2C532%2C%2C%2C1%2C%2C0%2C%2C%2C%2C%2C2%2C1%2C188324205%2CEND
20:08:30.009 FATAL: Uncaught exception
    err: {
      "type": "Error",
      "message": "Invalid manifest",
      "stack":
          Error: Invalid manifest
              at parse (C:\snapshot\streamyx\packages\dasha\dasha.js)
              at fetchManifest (C:\snapshot\streamyx\dist\src\app\downloader.js)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
              at async Downloader.start (C:\snapshot\streamyx\dist\src\app\downloader.js)
              at async Object.download (C:\snapshot\streamyx\dist\src\app\app.js)
              at async startCli (C:\snapshot\streamyx\dist\src\app\main.js)
    }
'130' is not recognized as an internal or external command,
operable program or batch file.
'rrsip' is not recognized as an internal or external command,
operable program or batch file.
'zoneoffset' is not recognized as an internal or external command,
operable program or batch file.
'devkbps' is not recognized as an internal or external command,
operable program or batch file.
'servicetype' is not recognized as an internal or external command,
operable program or batch file.
'servicetype' is not recognized as an internal or external command,
operable program or batch file.
'limitflux' is not recognized as an internal or external command,
operable program or batch file.
'limitdur' is not recognized as an internal or external command,
operable program or batch file.
'tenantId' is not recognized as an internal or external command,
operable program or batch file.
'GuardEncType' is not recognized as an internal or external command,
operable program or batch file.
'from' is not recognized as an internal or external command,
operable program or batch file.
'validdev' is not recognized as an internal or external command,
operable program or batch file.
'hms_devid' is not recognized as an internal or external command,
operable program or batch file.
'pbf' is not recognized as an internal or external command,
operable program or batch file.
'vqe' is not recognized as an internal or external command,
operable program or batch file.
'app_version' is not recognized as an internal or external command,
operable program or batch file.
'custom_sid' is not recognized as an internal or external command,
operable program or batch file.
'uid' is not recognized as an internal or external command,
operable program or batch file.
'sw_lh' is not recognized as an internal or external command,
operable program or batch file.
'srv' is not recognized as an internal or external command,
operable program or batch file.
'sw_h1' is not recognized as an internal or external command,
operable program or batch file.
'srv2' is not recognized as an internal or external command,
operable program or batch file.
'sw_h2' is not recognized as an internal or external command,
operable program or batch file.
'proxy' is not recognized as an internal or external command,
operable program or batch file.
'sw_st' is not recognized as an internal or external command,
operable program or batch file.
'st' is not recognized as an internal or external command,
operable program or batch file.
'accountinfo' is not recognized as an internal or external command,

**Comment by vitalygashkov** [comment]
> C:\Users\xxx\OneDrive\Masaüstü>sx.exe [https://switch-api.tvplus.com.tr](https://switch-api.tvplus.com.tr/pv/176.235.2.73:80/izmottrrs.tvplus.com.tr/88888888/16/20240815/268591865/268591865.mpd?allcentermount=30,1000001&130,1000002=&rrsip=gbzottrrs.tvplus.com.tr:443&zoneoffset=0&devkbps=190-15000&servicetype=0&servicetype=0&limitflux=-1&limitdur=-1&tenantId=9001&GuardEncType=2&from=31&validdev=5270,5510&hms_devid=5270&pbf=2_1_1_3382915255&vqe=3&app_version=chrome,WebTV,OSVersion=Win32,AppVersion=5.2.6.1,webtv&custom_sid=MTAxMjA2MjA2Nzg3&uid=pgkYL5eEYIhLfFmM6XZOQQ&sw_lh=9nA2sphTybCAls4_k-dq0Q&srv=cHYtYXZyLXMwMi50dnBsdXMuY29tLnRy&sw_h1=U5UTjIXVOCkNwRS3sXVrKg&srv2=cHYtYXZyLXMwMS50dnBsdXMuY29tLnRy&sw_h2=1nmVCIL2PoBgujVTj2QRYg&proxy=true&sw_st=yEv7-Lq6OV33UGKnotvsGoNI5g6tNdnWsIvR_Ddu_Zk&st=OrgoJor2lGAsiB439Aw9aWEiXuVNScyPgf3XKDxBUTI&accountinfo=MC69Mu6X0e+zyQL8Aa6VVTQRgAVp0WMvVhVv9ROGG3p3dSpffkYLK+7yjdk%2FZKfRyUb6HGJ9WB6MX3WLJ2i+BjvpPpen5Og5TgElqK4XPigck64KeYOcZ98QNWG%2Faba6KLAA7Q86GebOs+46M+6x6dsfWNvKG78avpiG0Eh9H0QvltXevcrQbI%2FmCSMmqY%2FG%3A20240831170809%3AUTC%2C%2C%2C20240831170809%2CMBOX020240815%2C%2C-1%2C1%2C0%2C%2C%2C1%2C532%2C%2C%2C1%2C%2C0%2C%2C%2C%2C%2C2%2C1%2C188324205%2CEND)

Use quotation marks around URL: `sx.exe "https://switch-api.tvplus.com.tr/pv..."`

**Comment by vitalygashkov** [comment]
> C:\Users\xxx\OneDrive\Masaüstü>sx.exe [https://turkey-edge5.mubicdn.net/](https://turkey-edge5.mubicdn.net/stream/c5005d5d4273f82d0415d93ca8584225/66d3be41/bf9cdc15/mubi-films/398452/faruk_tur_zxx_1920x960_50000_mezz45254/7e0b2b450a/drm_playlist.e19c2de7ee.ism/default/ver1.AVC1.2160p.ex-eac3.mpd)

Fixed in [v4.rc.2](https://github.com/vitalygashkov/streamyx/releases/tag/v4.0.0-rc.2)

**Comment by rinrinx** [comment]
How can we add subtitles and all sounds in mpd as softsub for mubi or any other platform, thank you

**Comment by rinrinx** [comment]
C:\Users\xxx\OneDrive\Masaüstü>sx.exe https://turkey-edge5.mubicdn.net/stream/c5005d5d4273f82d0415d93ca8584225/66d3be41/bf9cdc15/mubi-films/398452/faruk_tur_zxx_1920x960_50000_mezz45254/7e0b2b450a/drm_playlist.e19c2de7ee.ism/default/ver1.AVC1.2160p.ex-eac3.mpd
17:57:26.216 INFO : ✔ turkey-edge5.mubicdn.net-video-avc1.640028-5500209-1-video5500209.1080p.WEB-DL.x264 ∙ VIDEO ∙ 1920x960 ∙ 5500 KiB/s ∙ ~4003 MiB
17:57:28.026 INFO : ✔ turkey-edge5.mubicdn.net-video-avc1.640028-5500209-1-video5500209.1080p.WEB-DL.x264 ∙ AUDIO ∙ TR ∙ 320 KiB/s ∙ ~233 MiB
17:57:29.812 INFO : ✔ turkey-edge5.mubicdn.net-video-avc1.640028-5500209-1-video5500209.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ EN
17:57:32.517 INFO : ✖ Muxing failed. Output file not found: C:\Users\xx\Downloads\turkey-edge5.mubicdn.net-video-avc1.640028-5500209-1-video5500209.1080p.WEB-DL.x264\turkey-edge5.mubicdn.net-video-avc1.640028-5500209-1-video5500209.1080p.WEB-DL.x264.mkv

mux  problem

**Comment by rinrinx** [comment]
C:\Users\xxx\OneDrive\Masaüstü>sx.exe https://turkey-edge7.mubicdn.net/stream/161600e0306b8f2a95691cb01955ea26/66d3cb05/7c76cae1/mubi-films/126/the-edge-of-he_deu_zxx_1920x1080_50000_mezz41103/6d758d8c2d/drm_playlist.11d9c0e3a5.ism/default/ver1.AVC1.2160p.mpd --key 163d04042b2f449fa83d96f57e423909:2922db9ab70f2281269c6efa433badde
18:03:41.954 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ VIDEO ∙ 1920x1080 ∙ 5500 KiB/s ∙ ~4777 MiB
18:03:44.130 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ AUDIO ∙ DE ∙ 312 KiB/s ∙ ~271 MiB
18:03:46.132 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ DE
18:03:48.260 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ EN
18:03:50.208 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ FR
18:03:52.228 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ NL
18:03:54.049 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ PT
18:03:56.097 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ ES
18:03:58.239 INFO : ✔ turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264 ∙ SUBTITLES ∙ TR
18:04:00.057 INFO : ⠋ Decrypting21:04:00.059 INFO : Downloading Shaka Packager...
18:04:00.057 INFO : ✖ Decryption failed. Unable to find some final decrypted files: \\?\C:\Users\xxx\Downloads\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264.turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video=5500383.dec.mp4, \\?\C:\Users\xxx\Downloads\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264.turkey-edge7.mubicdn.net-audio-mp4a.40.2-311681-de-1-audio_deu=311681.dec.m4a
18:04:01.374 INFO : ✖ Muxing failed. Output file not found: C:\Users\ahmed\Downloads\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264\turkey-edge7.mubicdn.net-video-avc1.640028-5500383-1-video5500383.1080p.WEB-DL.x264.mkv

**Comment by rinrinx** [comment]
C:\Users\xxx\OneDrive\Masaüstü>sx.exe "https://switch-api.tvplus.com.tr/pv/176.235.9.133:80/izmottrrs.tvplus.com.tr/88888888/16/20240815/268592411/268592411.mpd?allcentermount=30,1000001&130,1000002=&rrsip=gbzottrrs.tvplus.com.tr:443&zoneoffset=0&devkbps=190-15000&servicetype=0&servicetype=0&limitflux=-1&limitdur=-1&tenantId=9001&GuardEncType=2&from=31&validdev=5276,5271&hms_devid=5276&pbf=2_1_1_3350482220&vqe=3&app_version=chrome,WebTV,OSVersion=Win32,AppVersion=5.2.6.1,webtv&custom_sid=MTAxMjA2MjA2Nzg3&uid=geA2S4vm1jHG6oPBJYRKww&sw_lh=9nA2sphTybCAls4_k-dq0Q&srv=cHYtYW5rLXMwMS50dnBsdXMuY29tLnRy&sw_h1=qFpQAEEfKt44qA9nOqVKDw&srv2=cHYtYXZyLXMwMS50dnBsdXMuY29tLnRy&sw_h2=1nmVCIL2PoBgujVTj2QRYg&proxy=true&sw_st=luOEsGUpHIrX4PbneajGg7nuVdDJ0ZJPWObyBu0o4h8&st=spwgjfTLcV-TfF8Tl4ltNYBhmnXD0wyyt3z11MVj3Us&accountinfo=tFbHPJTGYkn7Kllkrcck+m1yQNy+DmAxf4iefVcfc9l3dSpffkYLK+7yjdk%2FZKfRyUb6HGJ9WB6MX3WLJ2i+BjvpPpen5Og5TgElqK4XPigck64KeYOcZ98QNWG%2Faba6AAg5fj9Nq5o2D9ne34ujitsfWNvKG78avpiG0Eh9H0QvltXevcrQbI%2FmCSMmqY%2FG%3A20240831181156%3AUTC%2C%2C%2C20240831181156%2CAMZN20240816101%2C%2C-1%2C1%2C0%2C%2C1%2C1%2C532%2C%2C188323748%2C1%2C%2C0%2C%2C%2C%2C%2C2%2C1%2C188324650%2CEND" --key 11862aada512fdc7778d561ee7f5a1ee:c2465f6a89f419a6509e2501db740c39
18:16:45.446 INFO : ✔ pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264 ∙ VIDEO ∙ 1920x1080 ∙ 6000 KiB/s ∙ ~3011 MiB
18:17:39.133 INFO : ✔ pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264 ∙ AUDIO ∙ TUR ∙ 128 KiB/s ∙ ~64 MiB
18:17:41.664 INFO : ✔ pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264 ∙ AUDIO ∙ ENG ∙ 128 KiB/s ∙ ~64 MiB
18:17:44.454 INFO : ✔ pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264 ∙ SUBTITLES
18:17:46.655 INFO : ✔ pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264 ∙ SUBTITLES
18:17:49.066 INFO : ✔ Decrypted



18:18:00.787 INFO : ✖ Muxing failed. Output file not found: C:\Users\xxx\Downloads\pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264\pv-ank-s01.tvplus.com.tr-video-avc1.4d4028-6000000-0-4.1080p.WEB-DL.x264.mkv

**Comment by rinrinx** [comment]
mux promblem why

**Comment by rinrinx** [comment]
output is probably a problem so you can add -o as well as output

**Comment by vitalygashkov** [comment]
https://github.com/vitalygashkov/streamyx/issues/202#issuecomment-2323004254

Fixed in [v4-rc.3](https://github.com/vitalygashkov/streamyx/releases/tag/cli-v4.0.0-rc.3)

**Comment by vitalygashkov** [comment]
https://github.com/vitalygashkov/streamyx/issues/202#issuecomment-2322997647

The mubi service's mpd links are no longer available. I need a new log (with a link, preferably one that is always available for all regions) to reproduce the bug if it is still present.
