### ISSUE TITLE
Add mode to just show all nessesary data without actual download

### ISSUE THREAD

**Issue by zhenyahacker** [vitalygashkov/streamyx#51]
Suggestion to add a one mode (exec flag), which will obtain all nessesary data, but instead of downloading just print it on screen. Maybe, print as json to easily pass it to another app.

**Comment by zhenyahacker** [comment]
Yep, that`s great. Please, make it print all the subtitles links to debug output.

**Comment by iamDarkAdam** [comment]
> --debug --skip-audio --skip-video --skip-subtitles --skip-muxing

--skip-subs --skip-mux

**Comment by vitalygashkov** [comment]
> Please, make it print all the subtitles links to debug output.

Landed in [v3.6.37](https://github.com/vitalygashkov/streamyx/releases/tag/v3.6.37).
