### ISSUE TITLE
Windows: поддержка кириллицы

### ISSUE THREAD

**Issue by USEROK2024** [vitalygashkov/streamyx#59]
После автоматического ввода ключа, при попытке decrypt, все скачанные файлы исчезают, напрмер эта ссылка https://okko.tv/serial/cheljuskin-zadanie-imperatora . Поправьте пожалуйста или подскажите как изменить название папки при скачивании на латиницу.

**Comment by vitalygashkov** [comment]
На Windows люди сталкивались с подобной проблемой. Решалась она так:

Перейти в Панель управления → Региональные стандарты → Дополнительно → Изменить язык системы.
Поставить флажок Бета-версия: Использовать Юникод (UTF-8) для поддержки языка во всем мире.

В будущем постараюсь найти решение, чтобы не было необходимости выставлять эту настройку.

**Comment by vitalygashkov** [comment]
> Перейти в Панель управления → Региональные стандарты → Дополнительно → Изменить язык системы. Поставить флажок Бета-версия: Использовать Юникод (UTF-8) для поддержки языка во всем мире.

Для корректного вывода кириллицы в логах терминала нужно включить поддержку Юникода в системе.
