### ISSUE TITLE
Which FFmpeg version is required?

### ISSUE THREAD

**Issue by FiftyFour7250** [vitalygashkov/streamyx#60]
If I leave the files folder empty, then everything downloads perfectly. If I put device_client_id_blob, device_private_key, mp4decrypt.exe and ffmpeg.exe there, then it's written in logs that the decryption is successful, and even the KID:KEY is correct, but as soon as it comes to "Muxing", the application crashes without saving anything. 

So I think the problem in FFmpeg. Which version do I need to put in the files folder? Give me a direct link to it please. And this is only one file "ffmpeg.exe ", or is there anything else?

**Comment by vitalygashkov** [comment]
Single executable (ffmpeg.exe) is enough. I think any relatively recent versions will do (released within the last year).

There are problems with Cyrillic characters in file names on Windows, which may be related to ffmpeg. To solve this, you need to enable beta support for Unicode characters. This may be the issue.

**Comment by FiftyFour7250** [comment]
Да, помогло это решение
https://github.com/vitalygashkov/streamyx/issues/59#issuecomment-1890931906
Несмотря на то, что в названии папок, где лежит софт не было кириллицы - она была в автоматически создаваемой папке с именем самого контента, название которого на кириллице. В этом и была проблема.
