### ISSUE TITLE
Wink не скачивает после ввода номера телефона и подтверждения кодом

### ISSUE THREAD

**Issue by JustAndreww** [vitalygashkov/streamyx#62]
```
2024-2-19 12:37:21 INFO
2024-2-19 12:37:21 ERROR  Failed to parse message as SignedMessage
2024-2-19 12:37:21 ERROR  Unable to parse license - check protobufs

2024-2-19 12:54:49 DEBUG  Creating session
2024-2-19 12:54:49 DEBUG  Building license request
2024-2-19 12:54:49 DEBUG  Signing license request
2024-2-19 12:54:49 DEBUG  License request created
2024-2-19 12:54:49 DEBUG  Sending message request for session XXX of type 0
2024-2-19 12:54:49 ERROR  Failed to parse message as SignedMessage
2024-2-19 12:54:49 DEBUG  Updating session XXX of message type undefined
2024-2-19 12:54:49 ERROR  Unable to parse license - check protobufs
```

streamyx/3.6.34 win32-x64 node-v18.5.0

**Comment by JustAndreww** [comment]
Сообщение об ошибке точно такое же осталось. Поведение не изменилось как будто бы.

**Comment by vitalygashkov** [comment]
> Сообщение об ошибке точно такое же осталось. Поведение не изменилось как будто бы.

В v3.6.36 должно быть поправлено. Если нет, то нужно больше информации об ошибке и подробный сценарий по воспроизведению: какую ссылку вставляете, с какими аргументами, и полный лог/скриншоты результатов.

**Comment by JustAndreww** [comment]
Полный листинг на v3.6.36:
```
E:\Soft\Video\widevine-l3-decryptor\working\streamyx>streamyx-win-x64.exe -d
URL: https://wink.ru/movies/posledniy-geroy-year-1992
2024-2-24 21:40:19 DEBUG  Loading auth config
2024-2-24 21:40:19 DEBUG  Requesting credentials
2024-2-24 21:40:19 DEBUG  Checking auth config
2024-2-24 21:40:21 DEBUG  Getting data from https://sib-krsn-itv05.svc.iptv.rt.ru/api/v3/user/media_items/97353529...
2024-2-24 21:40:23 DEBUG  Manifest URL: https://s35761.cdn.ngenix.net/mdrm/sd_1992_posledniy_geroy__ar2_xOIEwhnYXJE_film/b509d023/manifest.mpd
2024-2-24 21:40:23 INFO   Последний герой
2024-2-24 21:40:23 DEBUG  Creating session
2024-2-24 21:40:23 DEBUG  Building license request
2024-2-24 21:40:23 DEBUG  Signing license request
2024-2-24 21:40:23 DEBUG  License request created
2024-2-24 21:40:23 DEBUG  Sending message request for session xxx00000000000000 of type 0
2024-2-24 21:40:23 ERROR  Failed to parse message as SignedMessage
2024-2-24 21:40:23 DEBUG  Updating session xxx00000000000000 of message type undefined
2024-2-24 21:40:23 ERROR  Unable to parse license - check protobufs
```

**Comment by vitalygashkov** [comment]
> Полный листинг на v3.6.36:
> 
> ```
> streamyx-win-x64.exe -d
> URL: https://wink.ru/movies/posledniy-geroy-year-1992
> 2024-2-24 21:40:19 DEBUG  Loading auth config
> 2024-2-24 21:40:19 DEBUG  Requesting credentials
> 2024-2-24 21:40:19 DEBUG  Checking auth config
> 2024-2-24 21:40:21 DEBUG  Getting data from https://sib-krsn-itv05.svc.iptv.rt.ru/api/v3/user/media_items/97353529...
> 2024-2-24 21:40:23 DEBUG  Manifest URL: https://s35761.cdn.ngenix.net/mdrm/sd_1992_posledniy_geroy__ar2_xOIEwhnYXJE_film/b509d023/manifest.mpd
> 2024-2-24 21:40:23 INFO   Последний герой
> 2024-2-24 21:40:23 DEBUG  Creating session
> 2024-2-24 21:40:23 DEBUG  Building license request
> 2024-2-24 21:40:23 DEBUG  Signing license request
> 2024-2-24 21:40:23 DEBUG  License request created
> 2024-2-24 21:40:23 DEBUG  Sending message request for session xxx00000000000000 of type 0
> 2024-2-24 21:40:23 ERROR  Failed to parse message as SignedMessage
> 2024-2-24 21:40:23 DEBUG  Updating session xxx00000000000000 of message type undefined
> 2024-2-24 21:40:23 ERROR  Unable to parse license - check protobufs
> ```

Файлы device_client_id_blob и device_private_key точно актуальны и не отозваны Гуглом? На других сервисах дешифровка контента работает?

**Comment by JustAndreww** [comment]
Вроде как да, с КП качал. А есть 100% способ проверить что дело не в отозванном CDM?

**Comment by vitalygashkov** [comment]
> Вроде как да, с КП качал. А есть 100% способ проверить что дело не в отозванном CDM?

Я потому и спросил какой сейчас (а не когда-то в прошлом) результат при скачивании через Streamyx в других сервисах (Okko, Кинопоиск)? Если везде подобная ошибка, то высока вероятность, что отозвали. Можем убедиться наверняка, если скинете файлы device_..., я подставлю их у себя и попробую запустить закачку. Либо с кем-нибудь из знакомых такое проверните.

**Comment by JustAndreww** [comment]
Да, с КП качает прямо сейчас и всё ок. Декодируется тоже нормально.

Кстати, можно же сделать декодинг параллельно скачиванию. К моменту скачивания последних дорожек первые уже будут декодированы :)
