### ISSUE TITLE
Registration for Okko is not available. Anti-bot is enabled

### ISSUE THREAD

**Issue by iamDarkAdam** [vitalygashkov/streamyx#63]
```
DEBUG  Loading auth config
DEBUG  Checking auth config
DEBUG  Logging
ERROR  Antibot system is active. Failed to complete the request
```

It looks like this is the end

**Comment by vitalygashkov** [comment]
Problem may be related to the location. Try using a Russian VPN if you are not in Russia.

**Comment by iamDarkAdam** [comment]
> Problem may be related to the location. Try using a Russian VPN if you are not in Russia.

This didn't help to solve the problem. Maybe Okko has blocked all my ip addresses.
