### ISSUE TITLE
Cannot create CDM adapter

### ISSUE THREAD

**Issue by telenkor** [vitalygashkov/streamyx#64]
Версия 3.6.34 работала до недавнего времени, а теперь на Кинопоиске выдает: Cannot create CDM adapter.
Ключи забанили или что-то другое?
Лог пишет следующее:
```
2/19/2024, 9:29:16 DEBUG  Loading auth config
2/19/2024, 9:29:16 DEBUG  Requesting credentials
2/19/2024, 9:29:17 DEBUG  Checking auth...
2/19/2024, 9:29:17 DEBUG  Saving authorized state
2/19/2024, 9:29:18 DEBUG  Authorization cookies saved
2/19/2024, 9:29:18 DEBUG  Getting data from https://api.ott.kinopoisk.ru/v12/hd/content/a7ca6dfb03224dc3b5659d8b3029453b/metadata...
2/19/2024, 9:29:20 DEBUG  Getting data from https://api.ott.kinopoisk.ru/v12/hd/content/a7ca6dfb03224dc3b5659d8b3029453b/streams?serviceId=25...
2/19/2024, 9:29:21 DEBUG  Manifest URL: https://strm.yandex.ru/vod/vh-ottenc-converted/vod-content/........
2/19/2024, 9:29:21 INFO   Dobar vetar «Plava ptico»
2/19/2024, 9:29:21 DEBUG  Decryption keys could not be obtained
2/19/2024, 9:29:21 DEBUG  Trying to decrypt through a CDM adapter (slower process)
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 ERROR  Cannot create CDM adapter
2/19/2024, 9:29:21 INFO   VIDEO ∙ 1018x576 ∙ 2355 Kbps ∙ 1332 MiB
2/19/2024, 9:34:47 INFO   AUDIO ∙ RUS (Русский) ∙ 48 kHz ∙ 195 Kbps ∙ 111 MiB
```

А в Терминале такое:
```
/snapshot/streamyx/dist/src/downloader.js:48
        if (contentKeys.length) {
                        ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Downloader.start (/snapshot/streamyx/dist/src/downloader.js:48:25)
    at async download (/snapshot/streamyx/dist/streamyx.js:26:9)
    at async initialize (/snapshot/streamyx/dist/streamyx.js:41:9)
```

**Comment by iamDarkAdam** [comment]
Share the link to the movie

**Comment by iamDarkAdam** [comment]
Это работает, возможно у вас отозвали CDM

**Comment by telenkor** [comment]
>отозвали CDM
Какие в связи с этим можно предпринять шаги?

Например, https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b

**Comment by iamDarkAdam** [comment]
> > отозвали CDM
> 
> Какие в связи с этим можно предпринять шаги?
> 
> Например, https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b

Выпускать новые ключи

**Comment by telenkor** [comment]
> Выпускать новые ключи device_client_id_blob и device_private_key

Сделал новые ключи. Но поведение абсолютно аналогично «старым». Посмею предположить, что дело в чем-то другом, а не в ключах.
[Этот контент](https://hd.kinopoisk.ru/film/440028c0b9218710b89f84a6e4f2667d) скачивается и собирается без проблем.
[А этот](https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b) — ERROR  Cannot create CDM adapter.
И это не единственные пары работает/не работает. Такое же поведение было на других фильмах.

**Comment by iamDarkAdam** [comment]
> > Выпускать новые ключи device_client_id_blob и device_private_key
> 
> Сделал новые ключи. Но поведение абсолютно аналогично старым. Посмею предположить, что дело в чем-то другом, а не в ключах. [Этот контент](https://hd.kinopoisk.ru/film/440028c0b9218710b89f84a6e4f2667d) скачивается и собирается без проблем. [А этот](https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b) — ERROR Cannot create CDM adapter. И это не единственные пары работает/не работает. Такое же поведение было на других фильмах.

Где вы создавали ключи?

**Comment by telenkor** [comment]
> Где вы создавали ключи?

Самостоятельно в Андроид студии.

**Comment by iamDarkAdam** [comment]
> > Выпускать новые ключи device_client_id_blob и device_private_key
> 
> Сделал новые ключи. Но поведение абсолютно аналогично старым. Посмею предположить, что дело в чем-то другом, а не в ключах. [Этот контент](https://hd.kinopoisk.ru/film/440028c0b9218710b89f84a6e4f2667d) скачивается и собирается без проблем. [А этот](https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b) — ERROR Cannot create CDM adapter. И это не единственные пары работает/не работает. Такое же поведение было на других фильмах.

Первая ссылка на фильм без DRM, вторая с DRM, получается у вас все видео с DRM не загружаются?

**Comment by telenkor** [comment]
Получается так. Не знаю, что с этим делать.

**Comment by iamDarkAdam** [comment]
> Получается так. Не знаю, что с этим делать.

Вы используете MacOS?

**Comment by allpeoplen00bs** [comment]
> [А этот](https://hd.kinopoisk.ru/film/a7ca6dfb03224dc3b5659d8b3029453b) — ERROR Cannot create CDM adapter.

Проблема не повторилась, всё скачалось нормально

**Comment by telenkor** [comment]
> > Получается так. Не знаю, что с этим делать.
> 
> Вы используете MacOS?

Monterey 12.7.1

**Comment by iamDarkAdam** [comment]
> > > Получается так. Не знаю, что с этим делать.
> > 
> > 
> > Вы используете MacOS?
> 
> Monterey 12.7.1

Напишите [разработчику](https://linktr.ee/vitalygashkov) в telegram, он может воспроизвести проблему у себя.

**Comment by iamDarkAdam** [comment]
> > > Получается так. Не знаю, что с этим делать.
> > 
> > 
> > Вы используете MacOS?
> 
> Monterey 12.7.1 upd: попробовал на 10-й винде — ровно тоже самое.

Интересно, возможно ключи не правильно были созданы, до этого вам удавалось скачать контент с DRM?

**Comment by telenkor** [comment]
> Интересно, возможно ключи не правильно были созданы, до этого вам удавалось скачать контент с DRM?
По правде сказать, я полагал, что там у них весь контент с ДРМ.  В основном все было благополучно.

**Comment by iamDarkAdam** [comment]
> > Интересно, возможно ключи не правильно были созданы, до этого вам удавалось скачать контент с DRM?
> 
> По правде сказать, я полагал, что там у них весь контент с ДРМ. В основном все было благополучно.

покажите структуру папки files в папке streamyx

**Comment by iamDarkAdam** [comment]
Не вижу расширения файлов, возможно вы забыли удалить расширение у файлов device_client_id_blob и device_private_key ?

**Comment by telenkor** [comment]
![Снимок экрана 2024-02-20 в 12 54 27](https://github.com/vitalygashkov/streamyx/assets/31967374/6a5aaeb9-1e17-4d53-ab8c-66efabb8d6f0)

**Comment by iamDarkAdam** [comment]
> ![Снимок экрана 2024-02-20 в 12 54 27](https://private-user-images.githubusercontent.com/31967374/306216198-6a5aaeb9-1e17-4d53-ab8c-66efabb8d6f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjQ1NTgsIm5iZiI6MTcwODQyNDI1OCwicGF0aCI6Ii8zMTk2NzM3NC8zMDYyMTYxOTgtNmE1YWFlYjktMWUxNy00ZDUzLWFiOGMtNjZlZmFiYjhkNmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDEwMTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMGIzNGQ2ZDc3NzA0ZDhkZWIzMmUxYWQ2OTdjYWNmMWQzYzg5YjY3ZGViOWNhM2FiMjhmZmIwN2NkNGExNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.54YiXEeCKwLsxGXbxQ_ZaeuDQu2pn1vIxA9jfk0z-qY) Может, я вам как-то приватно, передам эти ключи, да вы попробуете? Ну, вдруг, они действительно получились какими-то не такими?

С ключами всё в порядке, работают, даже не знаю в чём проблема, может в ОС, напишите в телеграм разработчику, он тоже пользуется MacOS

**Comment by vitalygashkov** [comment]
В v3.6.36 добавил детальный вывод ошибки чтения файлов Widevine девайса. Стоит заново запустить и прислать результаты с логом/скрином ошибки сюда.

**Comment by vitalygashkov** [comment]
От автора:
> Попробовал.
> Никакой ошибки не вылезло и все скачалось
